<?php

namespace app\modules\apiv1\models;

use app\models\Productstock;

class Invoice extends \app\models\Invoice {

    public function fields() {
        return [
            'id',
            'dateCreate',
            'recycleBin',
            'iduser',
            'codigoModalidad',
            'idsale',
            'idpurchase',
            'cufd',
            'codigoControl',
            'cuis',
            'numeroFactura',
            'codigoEmision',
            'cuf',
            'codigoAmbiente',
            'codigoPuntoVenta',
            'codigoSistema',
            'codigoSucursal',
            'codigoDocumentoSector',
            'tipoFacturaDocumento',
            'archivo',
            'fechaEnvio',
            'hashArchivo',
            'codigoEstado',
            'codigoRecepcion',
            'transaccion',
            'codigoDescripcion',
            'codigosRespuestas',
            'nitEmisor',
            'razonSocialEmisor',
            'municipio',
            'telefono',
            'direccion',
            'fechaEmision',
            'nombreRazonSocial',
            'codigoTipoDocumentoIdentidad',
            'numeroDocumento',
            'complemento',
            'codigoCliente',
            'codigoMetodoPago',
            'numeroTarjeta',
            'montoTotal',
            'montoTotalSujetoIva',
            'montoGiftCard',
            'descuentoAdicional',
            'codigoExcepcion',
            'cafc',
            'codigoMoneda',
            'tipoCambio',
            'montoTotalMoneda',
            'leyenda',
            'usuario',
            'fechaLimiteEmision',
            'cufdAnulacion',
            'responseAnulacion',
            'codigoDescripcionAnulacion',
            'codigoEstadoAnulacion',
            'transaccionAnulacion',
            'idcontingencia',
            'montoTotalDevuelto',
            'montoDescuentoCreditoDebito',
            'montoEfectivoCreditoDebito',
            'idinvoice',
            'masivaFactura',
            'idmasivaFactura',
        ];
    }
}